import { Dataset, DatasetDetails, User } from './types';

export const mockUser: User = {
  id: 'user-1',
  email: 'alex@example.com',
  name: 'Alex Johnson',
  avatar: undefined,
  createdAt: '2024-01-15T10:00:00Z',
  connectedAccounts: [
    { provider: 'kaggle', connected: false },
    { provider: 'github', connected: true, username: 'alexjohnson', connectedAt: '2024-02-01T10:00:00Z' },
    { provider: 'huggingface', connected: false },
  ],
  savedDatasets: ['ds-1', 'ds-3', 'ds-5'],
};

export const mockDatasets: Dataset[] = [
  {
    id: 'ds-1',
    title: 'Global COVID-19 Dataset',
    description: 'Comprehensive COVID-19 data including cases, deaths, and vaccinations by country and date.',
    source: 'kaggle',
    format: 'csv',
    size: '45.2 MB',
    sizeBytes: 47420825,
    relevanceScore: 96,
    qualityScore: 'high',
    downloadUrl: 'https://example.com/download/ds-1',
    tags: ['healthcare', 'covid-19', 'time-series', 'global'],
    lastUpdated: '2024-01-20T00:00:00Z',
    author: 'Johns Hopkins University',
    license: 'CC BY 4.0',
  },
  {
    id: 'ds-2',
    title: 'E-commerce Customer Behavior',
    description: 'Customer transaction data from an e-commerce platform including purchase history and browsing patterns.',
    source: 'github',
    format: 'json',
    size: '128.5 MB',
    sizeBytes: 134742016,
    relevanceScore: 89,
    qualityScore: 'high',
    downloadUrl: 'https://example.com/download/ds-2',
    tags: ['e-commerce', 'customer-behavior', 'transactions'],
    lastUpdated: '2024-01-18T00:00:00Z',
    author: 'DataScience Community',
    license: 'MIT',
  },
  {
    id: 'ds-3',
    title: 'US Housing Prices 2010-2024',
    description: 'Historical housing prices across major US metropolitan areas with demographic features.',
    source: 'government',
    format: 'csv',
    size: '89.1 MB',
    sizeBytes: 93429350,
    relevanceScore: 85,
    qualityScore: 'high',
    downloadUrl: 'https://example.com/download/ds-3',
    tags: ['real-estate', 'housing', 'economics', 'usa'],
    lastUpdated: '2024-01-15T00:00:00Z',
    author: 'US Census Bureau',
    license: 'Public Domain',
  },
  {
    id: 'ds-4',
    title: 'NLP Sentiment Analysis Dataset',
    description: 'Labeled dataset for sentiment analysis with 500k+ reviews from various sources.',
    source: 'huggingface',
    format: 'parquet',
    size: '2.3 GB',
    sizeBytes: 2469606195,
    relevanceScore: 82,
    qualityScore: 'medium',
    downloadUrl: 'https://example.com/download/ds-4',
    tags: ['nlp', 'sentiment', 'text-classification', 'reviews'],
    lastUpdated: '2024-01-10T00:00:00Z',
    author: 'HuggingFace Community',
    license: 'Apache 2.0',
  },
  {
    id: 'ds-5',
    title: 'Stock Market Historical Data',
    description: 'Daily stock prices and trading volumes for S&P 500 companies from 2000 to present.',
    source: 'kaggle',
    format: 'csv',
    size: '156.8 MB',
    sizeBytes: 164446617,
    relevanceScore: 78,
    qualityScore: 'high',
    downloadUrl: 'https://example.com/download/ds-5',
    tags: ['finance', 'stocks', 'time-series', 'trading'],
    lastUpdated: '2024-01-22T00:00:00Z',
    author: 'FinanceData Labs',
    license: 'CC BY-NC 4.0',
  },
  {
    id: 'ds-6',
    title: 'Climate Change Indicators',
    description: 'Global climate indicators including temperature, CO2 levels, and sea level measurements.',
    source: 'government',
    format: 'json',
    size: '34.7 MB',
    sizeBytes: 36385792,
    relevanceScore: 75,
    qualityScore: 'high',
    downloadUrl: 'https://example.com/download/ds-6',
    tags: ['climate', 'environment', 'global', 'time-series'],
    lastUpdated: '2024-01-05T00:00:00Z',
    author: 'NOAA',
    license: 'Public Domain',
  },
  {
    id: 'ds-7',
    title: 'Image Classification - Animals',
    description: 'Curated image dataset with 100+ animal species for computer vision tasks.',
    source: 'huggingface',
    format: 'parquet',
    size: '5.8 GB',
    sizeBytes: 6227020800,
    relevanceScore: 71,
    qualityScore: 'medium',
    downloadUrl: 'https://example.com/download/ds-7',
    tags: ['computer-vision', 'images', 'classification', 'animals'],
    lastUpdated: '2023-12-20T00:00:00Z',
    author: 'CV Research Group',
    license: 'CC BY 4.0',
  },
  {
    id: 'ds-8',
    title: 'Social Media Engagement Metrics',
    description: 'Anonymized social media post data with engagement metrics and content features.',
    source: 'github',
    format: 'csv',
    size: '67.3 MB',
    sizeBytes: 70577356,
    relevanceScore: 68,
    qualityScore: 'low',
    downloadUrl: 'https://example.com/download/ds-8',
    tags: ['social-media', 'engagement', 'marketing'],
    lastUpdated: '2023-12-15T00:00:00Z',
    author: 'SocialData Research',
    license: 'CC BY-NC 4.0',
  },
];

export const mockDatasetDetails: Record<string, DatasetDetails> = {
  'ds-1': {
    ...mockDatasets[0],
    metrics: {
      rows: 245892,
      columns: 14,
      missingPercent: 2.3,
      duplicatePercent: 0.1,
      columnTypes: [
        { name: 'date', type: 'date', nullCount: 0, uniqueCount: 1095 },
        { name: 'country', type: 'string', nullCount: 0, uniqueCount: 195 },
        { name: 'total_cases', type: 'number', nullCount: 1250, uniqueCount: 89234 },
        { name: 'new_cases', type: 'number', nullCount: 2100, uniqueCount: 45678 },
        { name: 'total_deaths', type: 'number', nullCount: 890, uniqueCount: 34521 },
        { name: 'new_deaths', type: 'number', nullCount: 1500, uniqueCount: 12345 },
        { name: 'total_vaccinations', type: 'number', nullCount: 45000, uniqueCount: 78901 },
        { name: 'population', type: 'number', nullCount: 0, uniqueCount: 195 },
      ],
      sampleData: [
        { date: '2024-01-15', country: 'United States', total_cases: 103436829, new_cases: 12456, total_deaths: 1127152, new_deaths: 89, total_vaccinations: 672891234, population: 331893745 },
        { date: '2024-01-15', country: 'Brazil', total_cases: 37519960, new_cases: 8934, total_deaths: 702421, new_deaths: 45, total_vaccinations: 498234567, population: 214326223 },
        { date: '2024-01-15', country: 'India', total_cases: 44690738, new_cases: 5678, total_deaths: 530779, new_deaths: 23, total_vaccinations: 2201234567, population: 1407563842 },
        { date: '2024-01-15', country: 'France', total_cases: 38997490, new_cases: 7234, total_deaths: 165686, new_deaths: 34, total_vaccinations: 154678901, population: 67874000 },
        { date: '2024-01-15', country: 'Germany', total_cases: 38437756, new_cases: 6123, total_deaths: 174979, new_deaths: 28, total_vaccinations: 192345678, population: 83240525 },
        { date: '2024-01-14', country: 'United States', total_cases: 103424373, new_cases: 15678, total_deaths: 1127063, new_deaths: 102, total_vaccinations: 672845123, population: 331893745 },
        { date: '2024-01-14', country: 'Brazil', total_cases: 37511026, new_cases: 9876, total_deaths: 702376, new_deaths: 52, total_vaccinations: 498189234, population: 214326223 },
        { date: '2024-01-14', country: 'India', total_cases: 44685060, new_cases: 4567, total_deaths: 530756, new_deaths: 19, total_vaccinations: 2201189234, population: 1407563842 },
        { date: '2024-01-14', country: 'France', total_cases: 38990256, new_cases: 8456, total_deaths: 165652, new_deaths: 41, total_vaccinations: 154623456, population: 67874000 },
        { date: '2024-01-14', country: 'Germany', total_cases: 38431633, new_cases: 7234, total_deaths: 174951, new_deaths: 35, total_vaccinations: 192289012, population: 83240525 },
      ],
    },
    correlations: [
      { column1: 'total_cases', column2: 'total_deaths', value: 0.89 },
      { column1: 'total_cases', column2: 'population', value: 0.72 },
      { column1: 'new_cases', column2: 'new_deaths', value: 0.67 },
      { column1: 'total_vaccinations', column2: 'population', value: 0.85 },
      { column1: 'total_deaths', column2: 'population', value: 0.58 },
    ],
    distributions: [
      {
        column: 'new_cases',
        bins: [
          { label: '0-1K', count: 45000 },
          { label: '1K-5K', count: 78000 },
          { label: '5K-10K', count: 52000 },
          { label: '10K-50K', count: 48000 },
          { label: '50K-100K', count: 15000 },
          { label: '100K+', count: 8000 },
        ],
      },
    ],
    mlRecommendation: {
      task: 'time-series',
      confidence: 92,
      suggestedModels: ['ARIMA', 'Prophet', 'LSTM', 'XGBoost'],
      targetColumn: 'new_cases',
      reasoning: 'The dataset contains temporal data with clear date indexing and multiple time-dependent features. Time series forecasting would be ideal for predicting future case counts.',
    },
  },
};

// Generate details for other datasets
mockDatasets.forEach((dataset) => {
  if (!mockDatasetDetails[dataset.id]) {
    mockDatasetDetails[dataset.id] = {
      ...dataset,
      metrics: {
        rows: Math.floor(Math.random() * 500000) + 10000,
        columns: Math.floor(Math.random() * 20) + 5,
        missingPercent: Math.round(Math.random() * 10 * 10) / 10,
        duplicatePercent: Math.round(Math.random() * 3 * 10) / 10,
        columnTypes: [
          { name: 'id', type: 'string', nullCount: 0, uniqueCount: 100000 },
          { name: 'value', type: 'number', nullCount: 500, uniqueCount: 45000 },
          { name: 'category', type: 'string', nullCount: 0, uniqueCount: 25 },
          { name: 'timestamp', type: 'date', nullCount: 100, uniqueCount: 50000 },
          { name: 'is_active', type: 'boolean', nullCount: 0, uniqueCount: 2 },
        ],
        sampleData: Array(10).fill(null).map((_, i) => ({
          id: `row-${i + 1}`,
          value: Math.floor(Math.random() * 10000),
          category: ['A', 'B', 'C', 'D'][Math.floor(Math.random() * 4)],
          timestamp: new Date(2024, 0, Math.floor(Math.random() * 30) + 1).toISOString().split('T')[0],
          is_active: Math.random() > 0.3,
        })),
      },
      correlations: [
        { column1: 'value', column2: 'category_encoded', value: 0.45 },
        { column1: 'value', column2: 'timestamp_day', value: 0.23 },
      ],
      distributions: [
        {
          column: 'value',
          bins: [
            { label: '0-2K', count: 25000 },
            { label: '2K-4K', count: 35000 },
            { label: '4K-6K', count: 28000 },
            { label: '6K-8K', count: 18000 },
            { label: '8K-10K', count: 12000 },
          ],
        },
      ],
      mlRecommendation: {
        task: dataset.tags.includes('time-series') ? 'time-series' : 
              dataset.tags.includes('classification') || dataset.tags.includes('nlp') ? 'classification' : 
              dataset.tags.includes('regression') ? 'regression' : 'classification',
        confidence: Math.floor(Math.random() * 20) + 75,
        suggestedModels: ['Random Forest', 'XGBoost', 'Neural Network', 'Logistic Regression'],
        targetColumn: 'value',
        reasoning: 'Based on the dataset structure and features, this appears to be suitable for supervised learning tasks.',
      },
    };
  }
});
